const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function openApp(){location.href="app.html"} function now(){return new Date().toLocaleString()}
function toast(t){let x=$("#toast"); if(!x)return;x.textContent=t;x.classList.add("show-toast");setTimeout(()=>x.classList.remove("show-toast"),2500)}
function showPage(id){$$(".page").forEach(p=>p.classList.remove("active-page"));$$("#"+id).classList.add("active-page");$$(".tab").forEach(t=>t.classList.toggle("active",t.dataset.page===id));$("#pageTitle").textContent=id==="dashboard"?"Dashboard":id.replace(/^./,c=>c.toUpperCase())}
$$(".tab").forEach(t=>t.onclick=()=>showPage(t.dataset.page));
function loadProfile(){let p=JSON.parse(localStorage.getItem("motoresqProfile")||"{}");["name","blood","medical","allergies","vehicle"].forEach(k=>{if($("#"+k))$("#"+k).value=p[k]||""})}
if($("#profileForm"))$("#profileForm").onsubmit=e=>{e.preventDefault();let p={};["name","blood","medical","allergies","vehicle"].forEach(k=>p[k]=$("#"+k).value.trim());localStorage.setItem("motoresqProfile",JSON.stringify(p));toast("Profile saved locally")}
function contacts(){return JSON.parse(localStorage.getItem("motoresqContacts")||"[]")} function renderContacts(){let list=$("#contactList");if(!list)return;let a=contacts();list.innerHTML=a.length?a.map((c,i)=>`<div class="contact"><div><b>${esc(c.name)}</b><br><small>${esc(c.phone)} • ${esc(c.relation)}</small></div><button class="delete" onclick="removeContact(${i})">Delete</button></div>`).join(""):'<p class="muted">No emergency contacts added yet.</p>'}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function removeContact(i){let a=contacts();a.splice(i,1);localStorage.setItem("motoresqContacts",JSON.stringify(a));renderContacts();toast("Contact removed")}
if($("#contactForm"))$("#contactForm").onsubmit=e=>{e.preventDefault();let a=contacts();a.push({name:$("#contactName").value,phone:$("#contactPhone").value,relation:$("#contactRelation").value});localStorage.setItem("motoresqContacts",JSON.stringify(a));e.target.reset();renderContacts();toast("Emergency contact added")}
function history(){return JSON.parse(localStorage.getItem("motoresqHistory")||"[]")}function renderHistory(){let h=$("#historyList");if(!h)return;let a=history();h.innerHTML=a.length?a.map(x=>`<div class="history-item"><div><b>${x.status}</b><br><small class="muted">${x.time}</small></div><span class="muted">${x.location}</span></div>`).join(""):'<p class="muted">No alerts yet. Try “Simulate Accident” from the dashboard.</p>'}
let interval;
function simulateAccident(){let modal=$("#modal");if(!modal)return;modal.classList.remove("hidden");let time=30;$("#modalContent").innerHTML=`<div class="sos-icon">🚨</div><p class="eyebrow">POSSIBLE ACCIDENT DETECTED</p><h2>Are you okay?</h2><p class="muted">Demo countdown. Cancel to stop the simulated alert.</p><div class="timer" id="timer">30</div><button class="cancel" onclick="cancelAlert()">Cancel Alert</button>`;clearInterval(interval);interval=setInterval(()=>{time--;let t=$("#timer");if(t)t.textContent=time;if(time<=0){clearInterval(interval);sendAlert()}},1000)}
function closeModal(){clearInterval(interval);$("#modal").classList.add("hidden")}
function cancelAlert(){clearInterval(interval);addHistory("Alert Cancelled");closeModal();$("#safeText").textContent="YOU ARE SAFE";toast("Alert cancelled")}
function sendAlert(){addHistory("SOS Alert Sent");$("#modalContent").innerHTML='<div class="sos-icon">📡</div><p class="eyebrow">DEMO COMPLETE</p><h2>SOS Alert Prepared</h2><p class="muted">In Phase 1, no real SMS or call is sent. A future backend/hardware phase would handle emergency delivery.</p><button class="primary" onclick="closeModal()">Close</button>';$("#safeText").textContent="SOS DEMO COMPLETED"}
function addHistory(status){let a=history();a.unshift({status,time:now(),location:"Demo location • 26.8467° N, 80.9462° E"});localStorage.setItem("motoresqHistory",JSON.stringify(a));renderHistory()}
function clock(){let c=$("#clock");if(c)c.textContent=new Date().toLocaleString()}setInterval(clock,1000);clock();loadProfile();renderContacts();renderHistory();
